// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Navbar from "./components/nav/Navbar";
// import Footer from "./components/footer/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Duranta Online Limited",
//   description: "Generated by Okobiz Solutions",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <Navbar />
//          <main className="pt-22 relative z-10">
//           {children}
//         </main>
//         <Footer />
//       </body>
//     </html>
//   );
// }
"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/nav/Navbar";
import Footer from "./components/footer/Footer";
import { usePathname } from "next/navigation";
import ScrollToTopButton from "./components/scrollbtn/page";
import WhatsAppButton from "./components/whatsup/page";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export default function RootLayout({ children }) {
  const pathname = usePathname();

  // Dashboard route detect
  const isDashboard = pathname.startsWith("/dashboard");

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Navbar only for non-dashboard routes */}
        {!isDashboard && <Navbar />}

        {/* main padding: non-dashboard routes e pt-22, dashboard e none */}
        <main className={isDashboard ? "relative z-10" : "pt-22 relative z-10"}>
          {children}
        </main>

        {/* Footer only for non-dashboard routes */}
        {!isDashboard && <Footer />}
        <ScrollToTopButton />
        <WhatsAppButton />
      </body>
    </html>
  );
}
